### PR TITLE
Spelling error 

### PR DESCRIPTION
**Pull request by vgavrilova**
Hello! I've found a small spelling error in the article about Eclipse IDE, so I decided to commit some changes (even though there is only one :D). Moreover, I wanted to try out creating new pull requests on Github. Hopefully it can be useful

### CODE REVIEW

**Comment by bkis** [comment]
Thanks, every character counts ;)

**Review by bkis — CHANGES_REQUESTED** [review]
The changes made are fine and will be merged :+1:  
But there is also a hidden binary file that was committed (by accident?): `.DS_Store` - this file should be removed from this PR before it is merged, as it doesn't belong in the repository.

**Comment by vgavrilova** [comment]
It seems to be a Mac problem, sorry :D It adds this file automatically to every commit. But now it should be fine.

**Review by bkis — APPROVED** [review]
:ok_hand:

**Comment by bkis** [comment]
@all-contributors please add @vgavrilova for bug

**Pull request merged**
